<?php

namespace AtaApp\AtaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AtaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtaRepository extends EntityRepository
{
}
