<?php

namespace AtaApp\AtaBundle\Repository;

use Doctrine\ORM\EntityRepository;
use VTT\UtilsBundle\Libraries\DataTable;
use AtaApp\AtaBundle\Entity;

/**
 * AtaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtaRepository extends EntityRepository
{
    
    public function save(Entity\Ata $ata)
    {
        try{
            $em = $this->_em;
            
            $em->persist($ata->getMunicipio());
            $em->flush();
            
            $em->persist($ata);
            $em->flush();
            
        } catch (\Exception $ex) {
            throw new \Exception($ex);
        }
    }
    
    public function ataPaginacao(DataTable &$dataTable)
    {
        $dq = $this->createQueryBuilder('A');
        
        
        if($dataTable->isLimitOffSetQuery()){
            $dq->setFirstResult($dataTable->getPaginaAtual())
                ->setMaxResults($dataTable->getQuantidadeItemPagina());
        }
        /*
        if(strlen($dataTable->getSearch()) > 0){        
            foreach($dataTable->getColumns() as $colunasDt){
                $fieldColumn = $colunasDt['name'];
                if($fieldColumn === 'descricao'){
                    $dq->orWhere($dq->expr()->like('upper(P.descricao)', ":{$fieldColumn}"))
                        ->setParameter($fieldColumn, sprintf('%%%s%%', \Util\HelpersBundle\Helpers\StringsHelper::toUpperCase($dataTable->getSearch())));
                }elseif($fieldColumn === 'codigo_barra'){
                    $dq->orWhere($dq->expr()->like('C.codigo', ":{$fieldColumn}"))
                        ->setParameter($fieldColumn, sprintf('%s%%', $dataTable->getSearch()));
                }
            }
        }
        
        switch ($dataTable->getColumnNameOrderBy()){
            case 'descricao':
                $columnOrder = 'P.descricao';
                break;
            case 'codigo_barra':
                $columnOrder = 'C.codigo';
                break;
        }
        
        if(isset($columnOrder)){
            $dq->orderBy($columnOrder, $dataTable->getTypeOrderBy());
        }     */

        $paginator = new \Doctrine\ORM\Tools\Pagination\Paginator($dq, true);
        
        $dataTable->paginationToPaginatorORM($paginator);

        return $paginator->getQuery()->getResult();
    }
}
