<?php

namespace AtaApp\AtaBundle\Repository;

use Doctrine\ORM\EntityRepository;
use VTT\UtilsBundle\Libraries\DataTableJs\DataTable;
use AtaApp\AtaBundle\Entity;

/**
 * AtaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtaRepository extends EntityRepository
{
    
    public function save(Entity\Ata $ata)
    {
        try{
            $this->_em->getRepository('AtaAppAtaBundle:Municipio')->save($ata->getMunicipio());

            if($ata->getId()){
               $municipio = $this->_em->getRepository('AtaAppAtaBundle:Municipio') ->find($ata->getMunicipio()->getId());
               $ata->setMunicipio($municipio);
               $this->_em->merge($ata);
            }else{                
                $this->_em->persist ($ata);
            }

            $this->_em->flush();
        } catch (\Exception $ex) {
            throw new \Exception($ex);
        }
    }
    
    public function totalRegistros()
    {
        $dq = $this->createQueryBuilder('Ata');
        $result = $dq->select($dq->expr()->count('Ata.id'))
                     ->getQuery()->getResult();

        return (int) $result[0][1];
    }
    
    public function ataPaginacao(DataTable &$dataTable)
    {
        $dq = $this->createQueryBuilder('Ata');
        $dq->leftJoin('Ata.telefones', 'Telefone');
        $dq->join('Ata.municipio', 'Municipio');
        
        
        if($dataTable->isLimitOffSetQuery()){
            $dq->setFirstResult($dataTable->getPaginaAtual())
                ->setMaxResults($dataTable->getQuantidadeItemPagina());
        }
        
        if(strlen($dataTable->getSearch()) > 0){        
            foreach($dataTable->getColumns() as $colunasDt){
                $fieldColumn = $colunasDt['name'];
                if($fieldColumn === 'descricao'){
                    $dq->orWhere($dq->expr()->like('Ata.nome', ":{$fieldColumn}"))
                        ->setParameter($fieldColumn, sprintf('%%%s%%', $dataTable->getSearch()));
                }elseif($fieldColumn === 'telefones'){
                    $fone = \VTT\UtilsBundle\Helpers\TelefoneUtilsVTT::format($dataTable->getSearch());
                    $dq->orWhere($dq->expr()->in('Telefone.numero', ":{$fieldColumn}"))
                       ->setParameter($fieldColumn, array($fone));
                }elseif ($fieldColumn === 'municipio') {
                    $dq->orWhere($dq->expr()->like('Municipio.nome', ":{$fieldColumn}"))
                       ->setParameter($fieldColumn,  sprintf('%%%s%%', $dataTable->getSearch()));
                }elseif ($fieldColumn === 'estado') {
                    $dq->orWhere($dq->expr()->eq('Municipio.sigla', ":estado"))
                       ->setParameter('estado', $dataTable->getSearch());
                }
            }
        }
        
        switch ($dataTable->getColumnNameOrderBy()){
            case 'descricao':
                $columnOrder = 'Ata.nome';
                break;
            case 'telefones':
                $columnOrder = 'Telefone.numero';
                break;
            case 'municipio':
                $columnOrder = 'Municipio.nome';
                break;
            case 'estado':
                $columnOrder = 'Municipio.sigla';
                break;
        }
        
        if(isset($columnOrder)){
            $dq->orderBy($columnOrder, $dataTable->getTypeOrderBy());
        }     

        $paginator = new \Doctrine\ORM\Tools\Pagination\Paginator($dq, true);
        
        $dataTable->paginationToPaginatorORM($paginator);

        return $paginator->getQuery()->getResult();
    }
    
    
    public function listExportacao()
    {
        $dq = $this->createQueryBuilder('Ata');
        
        $dq->join('Ata.municipio', 'Municipio');
        
        $dq->orderBy('Municipio.nome,Ata.nome', 'asc');
        
        return $dq->getQuery()->getResult();
    }
}
