services:
    event_app.ctr_construct:
        class: VTT\BaseControllerBundle\Listener\BaseControllerVTTListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        arguments: [@service_container]
        #calls: 
        #    -  [onKernelController, [@kernel.controller]]



